"""empty message

Revision ID: 37a5f6d7bec9
Revises: 7d8005a81573
Create Date: 2019-08-01 20:47:17.303185

"""

# revision identifiers, used by Alembic.
revision = '37a5f6d7bec9'
down_revision = '7d8005a81573'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
