"""empty message

Revision ID: 7d8005a81573
Revises: 8b031b1087fa
Create Date: 2019-08-01 20:37:52.695155

"""

# revision identifiers, used by Alembic.
revision = '7d8005a81573'
down_revision = '8b031b1087fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
